version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - sudo yum clean all
      - sudo yum update -y
      - sudo amazon-linux-extras enable nginx1
      - sudo yum install -y nginx

  pre_build:
    commands:
      - echo "Checking NGINX configuration..."
      - sudo nginx -t || true  # Validate NGINX config
      - echo "Starting NGINX..."
      - sudo nginx || true  # Start NGINX manually

  build:
    commands:
      - echo "Copying index.html to /var/www/html/"
      - sudo mkdir -p /var/www/html/
      - sudo cp index.html /var/www/html/
      - ls -l /var/www/html/

  post_build:
    commands:
      - aws s3 rm s3://anu-bucket01/demo-app-files/ --recursive 

artifacts:
  files:
     - index.html
     - appspec.yml
     - scripts/**  # Ensure all files inside scripts/ are included
  name: artifact.zip
  discard-paths: yes   # This ensures files are not stored with subdirectories in S3

  # Specify the S3 path where the artifact.zip will be uploaded
  base-directory: .  # If your files are in the root directory
  s3:
    bucket: anu-bucket01
    path: demo-app-files/artifact.zip  # Upload to the 'demo-app-files' folder in the bucket
