version: 0.2

phases:
  install:
    commands:
     - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install -y nginx
  pre_build:
    commands:
      echo Starting NGINX service
      - sudo systemctl enable nginx
      - sudo systemctl start nginx || (echo "NGINX failed to start" && sudo systemctl status nginx)
  build:
    commands:
      - echo "Listing current directory contents"
      - sudo ls -l  # Ensure index.html is present in the current directory
      # - echo "Checking /var/www/html/ directory"
      # - sudo ls -ld /var/www/html/  # Verify the target directory
      - sudo mkdir -p /var/www/html/  # Create the directory if it doesn't exist
      - sudo cp index.html /var/www/html/
      - ls -l /var/www/html
      - echo "Checking /var/www/html contents..."
      - ls -l /var/www/html
  post_build:
    commands:
      - echo Configuring NGINX
artifacts:
  files:
   - index.html
    - appspec.yml  
    - scripts/install_nginx.sh
    - scripts/start_nginx.sh   
  discard-paths: no  # Keep directory structure
  base-directory: /var/www/html   # Ensure files are picked up from the correct location
    # - index.html
  # discard-paths: yes  # This removes the source directory structure when uploading
  # base-directory: /var/www/html  # The directory to be used as the base for artifact upload
  # name: artifact.zip  # The name of the artifact (it will be a zip file in your case)
  # s3:
  #   bucket: anu-bucket01
  #   key: code_output_demo_app/artifact.zip  # Path where artifact will be uploaded

