version: 0.2

phases:
  install:
    commands:
      - echo Checking Amazon Linux Version
      - cat /etc/os-release
      - echo Installing nginx
      - sudo dnf update -y  # Use dnf instead of apt-get
      - sudo dnf install -y nginx  # Correct package manager for Amazon Linux 2023
  pre_build:
    commands:
      - echo Validating nginx configuration
      - sudo nginx -t
      - echo Checking for port conflicts
      - sudo lsof -i :80 || echo "No conflicts detected"
      - echo Starting nginx service
      - sudo systemctl start nginx
      - sudo systemctl enable nginx
  build:
    commands:
      - echo Build phase started on $(date)
      - echo Adding files to nginx root directory
      - sudo cp index.html /usr/share/nginx/html/  # Correct Nginx root directory for Amazon Linux
  post_build:
    commands:
      - echo Checking nginx service status
      - sudo systemctl status nginx || sudo journalctl -u nginx
artifacts:
  files:
    - index.html