version: 0.2

phases:
  install:
    commands:
      - sudo echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
      
  build:
    commands:
      - sudo echo Build started on date
      - sudo cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX
artifacts:
  files:
      - /var/www/html/index.html