version: 0.2

phases:
  install:
    commands:
      - echo Checking Amazon Linux Version
      - cat /etc/os-release  # Confirm the version of Amazon Linux
      - echo Installing NGINX
      - sudo yum update -y  # Update the system
      - sudo amazon-linux-extras enable nginx1 # Enable the Nginx package from Amazon Linux Extras
      - sudo yum install -y nginx  # Install Nginx after enabling it from Amazon Linux Extras
  pre_build:
    commands:
      - echo Validating nginx configuration
      - sudo nginx -t  # Test Nginx configuration
      - echo Checking for port conflicts
      - sudo lsof -i :80 || echo "No conflicts detected"
      - echo Starting nginx service
      - sudo systemctl start nginx
      - sudo systemctl enable nginx
  build:
    commands:
      - echo Build phase started on $(date)
      - echo Adding files to nginx root directory
      - sudo cp index.html /usr/share/nginx/html/  # Nginx root directory in Amazon Linux 2
  post_build:
    commands:
      - echo Checking nginx service status
      - sudo systemctl status nginx || sudo journalctl -u nginx  # Check nginx status if any issue occurs
artifacts:
  files:
    - index.html  # Include this file in the build artifacts