version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking if the folder exists in the S3 bucket"
      - aws s3 ls s3://anu-bucket01/demo-app-files/ || echo "Folder does not exist in S3."
      - echo "Cleaning up S3 folder contents"
      - aws s3 rm s3://anu-bucket01/demo-app-files/ --recursive || echo "Nothing to delete."
      - echo "Folder contents after cleanup"
      - aws s3 ls s3://anu-bucket01/demo-app-files/ || echo "No files remaining in folder."

  build:
    commands:
      - echo "Listing files in the current directory"
      - ls -al  # List files to verify they are in the correct place
      - echo "Listing files in 'scripts' directory"
      - ls -al scripts/  # List the files inside scripts/ folder
      - echo "Creating zip file"
      - zip -r artifact.zip index.html appspec.yml scripts/  # Create the zip file
      - echo "Listing contents of artifact.zip"
      - unzip -l artifact.zip  # Verify what’s inside the zip file

artifacts:
  files:
    - artifact.zip  # Ensure the artifact.zip is listed here
  name: artifact.zip  # Use the name you want for the artifact
  discard-paths: yes  # Don't preserve directory structure
  base-directory: .  # This is the base directory where files are being created
  s3:
    bucket: anu-bucket01
    path: demo-app-files/  # Path inside the bucket where artifact.zip will go

cache:
  paths:
    - '/tmp/**/*'
