version: 0.2

phases:
  build:
    commands:
      - echo "Starting build phase..."
      # List files in the current directory
      - ls -l /tmp
      - ls -l
      # Create demo-app-files directory if it doesn't exist
      - mkdir -p demo-app-files
      # List files in demo-app-files directory
      - ls -l demo-app-files/
      # Check if the file exists before copying it
      - if [ -f "my-artifact.tar.gz" ]; then cp my-artifact.tar.gz demo-app-files/; else echo "File not found!"; fi
      # List the files again to see if the copy was successful
      - ls -l demo-app-files/

artifacts:
  files:
    - demo-app-files/artifact.zip  # Path to the file inside demo-app-files
  discard-paths: yes  # Flatten the directory structure
  name: artifact.zip  # The name of the artifact
  s3:
    bucket: anu-bucket01
    path: demo-app-files/  # Path inside the S3 bucket where the artifact will go

cache:
  paths:
    - '/tmp/**/*'
