version: 0.2

phases:
  pre_build:
    commands:
      # Ensure we clean up the previous build in S3
      - echo "Removing old files from the S3 bucket"
      - aws s3 rm s3://anu-bucket01/demo-app-files/ --recursive
      - aws s3 ls s3://anu-bucket01/demo-app-files/  # Check if it's empty

  build:
    commands:
      - echo "Listing files in the current directory"
      - ls -al  # Ensure your files are in the current directory
      - echo "Listing files in the 'scripts' directory"
      - ls -al scripts/  # List files inside scripts/
      - echo "Create artifact.zip"
      - zip -r artifact.zip index.html appspec.yml scripts/  # Zip the files
      - echo "Verify contents of artifact.zip"
      - unzip -l artifact.zip  # List contents of the zip before uploading

artifacts:
  files:
    - artifact.zip  # Only include the artifact.zip in the output
  name: artifact.zip
  discard-paths: yes  # Don't keep the folder structure, files should be at the root of the zip
  base-directory: .    # This is the current directory. Adjust if needed
  s3:
    bucket: anu-bucket01
    path: demo-app-files/  # This is the target folder in S3, not inside the zip

cache:
  paths:
    - '/tmp/**/*'
