version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking if the folder exists in the S3 bucket"
      - aws s3 ls s3://anu-bucket01/demo-app-files/ || echo "Folder does not exist in S3."
      - echo "Cleaning up S3 folder contents"
      - aws s3 rm s3://anu-bucket01/demo-app-files/ --recursive || echo "Nothing to delete."
      - echo "Folder contents after cleanup"
      - aws s3 ls s3://anu-bucket01/demo-app-files/ || echo "No files remaining in folder."

  build:
    commands:
      - echo "Starting build phase..."
      # List all files in the current directory for debugging
      - ls -l
      # Create demo-app-files directory if it doesn't exist
      - mkdir -p demo-app-files
      # List files in the demo-app-files directory
      - ls -l demo-app-files/
      # If the file exists in the current directory, copy it to demo-app-files
      - cp my-artifact.tar.gz demo-app-files/  # This command will fail if the file is not present
      - ls -l demo-app-files/
artifacts:
  files:
    - demo-app-files/artifact.tar.gz  # Only include artifact.tar.gz in the artifact
  discard-paths: yes  # Flatten the file structure (no directories inside the zip)
  name: 'artifact.zip'  # This is the name of the artifact file
  s3:
    bucket: anu-bucket01
    path: demo-app-files/  # Path inside the bucket where the artifact will be uploaded

cache:
  paths:
    - '/tmp/**/*'

