version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking if the folder exists in the S3 bucket"
      - aws s3 ls s3://anu-bucket01/demo-app-files/ || echo "Folder does not exist in S3."
      - echo "Cleaning up S3 folder contents"
      - aws s3 rm s3://anu-bucket01/demo-app-files/ --recursive || echo "Nothing to delete."
      - echo "Folder contents after cleanup"
      - aws s3 ls s3://anu-bucket01/demo-app-files/ || echo "No files remaining in folder."

  build:
    commands:
      - echo "Listing files in the current directory"
      - ls -al  # List files to verify they are in the correct place
      - echo "Listing files in 'scripts' directory"
      - ls -al scripts/  # List the files inside scripts/ folder
      - echo "Creating tarball artifact.tar.gz"
      - tar -czf artifact.tar.gz index.html appspec.yml scripts/  # Create the tarball
      - echo "Listing contents of artifact.tar.gz"
      - tar -tzf artifact.tar.gz  # Verify what’s inside the tarball

artifacts:
  files:
    - demo-app-files/artifact.tar.gz  # Only include artifact.tar.gz in the artifact
  discard-paths: yes  # Flatten the file structure (no directories inside the zip)
  name: 'artifact.zip'  # This is the name of the artifact file
  s3:
    bucket: anu-bucket01
    path: demo-app-files/  # Path inside the bucket where the artifact will be uploaded

cache:
  paths:
    - '/tmp/**/*'

