version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking if the folder exists in the S3 bucket"
      - aws s3 ls s3://anu-bucket01/demo-app-files/ || echo "Folder does not exist in S3."
      - echo "Cleaning up S3 folder contents"
      - aws s3 rm s3://anu-bucket01/demo-app-files/ --recursive || echo "Nothing to delete."
      - echo "Folder contents after cleanup"
      - aws s3 ls s3://anu-bucket01/demo-app-files/ || echo "No files remaining in folder."

  build:
    commands:
      - echo "Listing files in the current directory"
      - ls -al  # List files to verify they are in the correct place
      - echo "Listing files in 'scripts' directory"
      - ls -al scripts/  # List the files inside scripts/ folder
      - echo "Creating tarball artifact.tar.gz"
      - tar -czf artifact.tar.gz index.html appspec.yml scripts/  # Create the tarball
      - echo "Listing contents of artifact.tar.gz"
      - tar -tzf artifact.tar.gz  # Verify what’s inside the tarball

artifacts:
  files:
    - artifact.tar.gz  # Upload the artifact.tar.gz only
  name: artifact.tar.gz  # Name of the artifact
  discard-paths: yes  # Don't preserve directory structure
  base-directory: .  # Current directory as base for the files to be included
  s3:
    bucket: anu-bucket01
    path: demo-app-files/  # Path inside the bucket where artifact.tar.gz will go

cache:
  paths:
    - '/tmp/**/*'
