version: 0.2

phases:
  install:
    commands:
     - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install -y nginx
  pre_build:
    commands:
      echo Starting NGINX service
      - sudo systemctl enable nginx
      - sudo systemctl start nginx || (echo "NGINX failed to start" && sudo systemctl status nginx)
  build:
    commands:
     - echo "Creating artifact directory"
      - mkdir -p artifacts
      - echo "Copying index.html to artifacts directory"
      - cp index.html artifacts/
      - echo "Copying appspec.yml to artifacts directory"
      - cp appspec.yml artifacts/
      - echo "Copying scripts folder to artifacts directory"
      - cp -r scripts artifacts/
      - echo "Checking artifacts directory before upload"
      - ls -R artifacts/
  post_build:
    commands:
      - echo "Build completed. Artifacts ready."
artifacts:
  files:
   - index.html
    - appspec.yml  
    - scripts/install_nginx.sh
    - scripts/start_nginx.sh   
  discard-paths: no  # Keep directory structure
  base-directory: artifacts  # Ensure files are picked up from the correct location
    # - index.html
  # discard-paths: yes  # This removes the source directory structure when uploading
  # base-directory: /var/www/html  # The directory to be used as the base for artifact upload
  # name: artifact.zip  # The name of the artifact (it will be a zip file in your case)
  # s3:
  #   bucket: anu-bucket01
  #   key: code_output_demo_app/artifact.zip  # Path where artifact will be uploaded

